### ISSUE TITLE
Issues running the experiment

### ISSUE THREAD

**Issue by kpratik41** [maxjiang93/space_time_pde#1]
Thanks for the amazing work. I tried running the code but I believe i am missing some dataset.
I ran download_data.sh script successfully and then I ran run_experiments.sh which gives me the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'data/train_data_placeholder.npz'

How is this data supposed to be generated?

**Comment by maxjiang93** [comment]
Hey Soheil can you take a look at this? @soheilesm

**Comment by soheilesm** [comment]
> Thanks for the amazing work. I tried running the code but I believe i am missing some dataset.
> I ran download_data.sh script successfully and then I ran run_experiments.sh which gives me the following error:
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'data/train_data_placeholder.npz'
> 
> How is this data supposed to be generated?

As the name indicated you had to just put the name of your dataset in place of 'train_data_placeholder.npz'. We noticed that the run script might seem too complicated, now we provide a simpler 'run_experiment.sh' script which you can easily run after downloading the dataset by running 'download_data.sh' script. Feel free to further change other options available as arguments in the 'train.py' script.
