### ISSUE TITLE
Issue in running run_experiment.sh

### ISSUE THREAD

**Issue by santoshsanu1** [maxjiang93/space_time_pde#2]
I downloaded the data by running `download_data.sh` and then run the experiment using `run_experiment.sh`. It gave following error. 

PS: It was run on google colab with GPU.
  
`Traceback (most recent call last):
  File "train.py", line 400, in <module>
    main()
  File "train.py", line 371, in main
    use_continuity=args.use_continuity)
  File "/content/space_time_pde/experiments/rb2d/physics.py", line 62, in get_rb2_pde_layer
    pde_layer.add_equation(eqn_str, eqn_name, subs_dict=subs_dict)
  File "../../src/pde.py", line 79, in add_equation
    set(self.out_vars)))
ValueError: Variables in the eqn_str ({w*0.12129077315330505+5.587935322792781e-11, u*0.14067453145980835+-0.0025140857324004173, b*0.24790656566619873+0.0009028007043525577, t, z, x}) does not match that of in_vars ({x, z, t}) and out_vars ({w, b, u, p})`

**Comment by maxjiang93** [comment]
@soheilesm Any chance you might know what this is referring to? I'm thinking this might be due to Google Colab.
@santoshsanu1 Are you observing this on a local server?

**Comment by soheilesm** [comment]
@santoshsanu1 I just used the current version of the repo, downloaded the data as well by running `download_data.sh` and then ran the experiment on my GPU using `run_experiment.sh` as well - It ran pretty fine, no errors, no issues on my side. I agree with @maxjiang93, it might be an issue with your Google Colab setup. We close this issue.
