### ISSUE TITLE
missing tools

### ISSUE THREAD

**Issue by waynezw0618** [maxjiang93/space_time_pde#3]
Hi Max
I read you paper about the meshfreeFlowNet. It is very interesting and good tool for. great job!
I am trying to play with it make some modifications for 1D or 1d spatial dimention+ time case. so I tried unet.py in the package, but it seems requires **utils** which can not be found in the src. besides, pde_test.py  requires **parameterized**, which is also missing. would you please share it with me? besides, I am wondering whether I just need unet.py instead of unet3d.py for 1D or 1d spatial dimention+ time cases?

Best
Wei

**Comment by lblk** [comment]
也许你可以先把from utils…一行注释掉，直接尝试运行，然后获得未定义内容的列表

然后去model_utils.py之类的地方看看有没有你需要的类？🙃

**Comment by waynezw0618** [comment]
cool! 对utils有效，但是我没法找到pde_test.py里的**parameterized**
```
 $ find . -type f |xargs grep parameterized
./local_implicit_grid_test.py:from parameterized import parameterized
./local_implicit_grid_test.py:    @parameterized.expand((
./local_implicit_grid_integration_test.py:from parameterized import parameterized
./local_implicit_grid_integration_test.py:    @parameterized.expand((
./pde_test.py:#from parameterized import parameterized
./pde_test.py:    @parameterized.expand((
./implicit_net_test.py:from parameterized import parameterized
./implicit_net_test.py:    @parameterized.expand((
./regular_nd_grid_interpolation_test.py:from parameterized import parameterized
./regular_nd_grid_interpolation_test.py:    @parameterized.expand((
```

此外unet 可以直接用 在1D+T的case上么，看上去unet3D是2D+T的。

**Comment by lblk** [comment]
问题1:parameterized?
好像是个外部模块，单独安装一下吧
问题2:3D?
我没太看懂你的问题，这个事情太久远了细节我记不清了，但是我觉得是**不可以直接用的**，<u>照着3D改一下嘛，算是创新点了（逃</u>

**Comment by waynezw0618** [comment]
parameterized 找到不啊。。。

**Comment by maxjiang93** [comment]
Just saw your comments. This computer doesn't have chinese input setup so I'll reply in English.

`parameterized` is an PyPI external package that can be easily installed.
```
pip install parameterized
```
Also it is only used in the unit tests so I don't think it will affect your actual usage of the MeshfreeFlowNet modules.

Let me know if this resolves your question.

**Comment by waynezw0618** [comment]
@maxjiang93 thanks for replying. 
for `parameterized`, do you mean this one(https://pypi.org/project/parameterized/)
besides, I am wondering whether `unet.py` works with the package for 1D+T case, or I need further implementation. 

Thanks

**Comment by maxjiang93** [comment]
If your problem is 1D + time, you can probably use the UNet as is, and pass in a (N, 1, T) tensor where N is the 1D spatial resolution and T is the number of time steps.

**Comment by waynezw0618** [comment]
great & thks for replying!
